import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[1,5,9]])
print("the given array = \n",a)
print("the max value of giver array",a.max())
print("the minimum value of the given array = ",b.min())
print("the sum of given array = ",a.sum())
print("the sum of given array = ",b.sum(axis=1))
print("the min value of axis = ",b.min(axis=1))
print("the max value of giver array",a.max(axis=1))
print ("thye sum of a &b = \n",a+b)
print ("thye diff of a &b = \n",a-b)
print ("thye multi of a &b = \n",a*b)
print ("thye square root of a= \n",a**2)
print ("thye cube root of b = \n",a**3)
print("the cumulative sum of array = ",a.cumsum())
print("the average of the given array = ",b.mean())
print("the transpose ofan array = ", a.transpose())
print("the cumulative sum of array = ",a.cumsum(axis =  1))
